### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by Krysbe** [homebridge-nhc2/homebridge-nhc2#1]
**Describe the bug**
Error during install
**Steps To Reproduce**
Try to install on Raspberry Pi

(node:2810) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.80-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-nhc2"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405

Regards, 

Chris

**Comment by wvanvlaenderen** [comment]
Hi Chris, could you try again with node >=11.0.0?

**Comment by wvanvlaenderen** [comment]
Hi Krysbe, could you try again with node >=11.0.0?

**Comment by Krysbe** [comment]
Thanks. 

But now I'm using Hoobs for Homebridge and everything was working fine with the 1.0.0

But now with the 1.1.0
