### ISSUE TITLE
homebridge-nhc2 issue on Synology

### ISSUE THREAD

**Issue by rudytixhon** [homebridge-nhc2/homebridge-nhc2#10]
Hello, 
I have:
- Installed **homebridge** on a Synology DS916+ following with the Oznu docker following this [procedure](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology).
- Installed your **homebridge-nhc2** plugin (v1.2.1) through the Config plugin of Homebridge 
- Activated the **connected service** on https://mynikohomecontrol.niko.eu/ and received my password
- The following **config.json**
{
    "bridge": {
        "name": "xxx",
        "username": "yyy",
        "port": 53849,
        "pin": "zzz"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "NHC2",
            "name": "NHC2",
            "host": "IP address of my NHC2 controller",
            "password": "password given by mynikohomecontrol"
        }
    ]
}

Homebridge starts well:
Loading 2 platforms...
[8/23/2020, 2:40:21 PM] [Config] Initializing config platform...
[8/23/2020, 2:40:21 PM] [Config] Running in Service Mode
[8/23/2020, 2:40:21 PM] [NHC2] Initializing NHC2 platform...
[8/23/2020, 2:40:21 PM] [NHC2] NHC2Platform finished initializing!
[8/23/2020, 2:40:21 PM] [NHC2] NHC2Platform 'didFinishLaunching'

I'm able to add the Homebridge to my iOs "Home" app but no devices are showing up.

What can I do?

R.

**Comment by MirandaPoth** [comment]
Hi there R, 
What sorts of Niko devices do you have? The plugin currently only supports lights and dimmers.
FYI I have got it running successfully on a Raspberry Pi, and I'm currently working on adding support for generic switch devices and venetian blinds in a separate fork of this plugin.
Miranda

**Comment by rudytixhon** [comment]
Hello!
It's mainly lights and dimmers + some power counters. 

The main Controller is NHC2 (550-00003) but the lights are NHC1 devices (550-00103, 550-00106 and 550-00340). Maybe this is causing the issue?

Rudy.

**Comment by rudytixhon** [comment]
I just tried to connect directly on the NHC2 controller with a MQTT client (MQTT Explorer) and I cannot connect, but I'm not sure if I am doing correctly the things.

![Capture d’écran 2020-08-23 à 20 47 54](https://user-images.githubusercontent.com/53615918/90986347-76cee080-e582-11ea-97ba-3351dbaed4c3.png)

**Comment by geani** [comment]
@rudytixhon try mqtt fx as program, mqtt explorer doesn't work either in my case
settings are correct in my opinion

**Comment by rudytixhon** [comment]
> @rudytixhon try mqtt fx as program, mqtt explorer doesn't work either in my case
> settings are correct in my opinion

Thanks for the proposal! I tried mqtt fx but no success either.
It just after that I realized that the TLS encryption was mandatory! I will do further test tomorrow

**Comment by rudytixhon** [comment]
Should I put something in the config.json to force the TLS encryption?

**Comment by rudytixhon** [comment]
I don't know why but by putting all the parameters explicitly, it worked (I can see all the accessories)!
{
            "platform": "NHC2",
            "name": "NHC2",
            "host": "192.168.1.62",
            "port": "8884",
            "clientid": "NHC2-homebridge",
            "username": "hobby",
            "password": "password"
        }

**Comment by MirandaPoth** [comment]
Excellent, well done! Thanks for sharing :-)

**Comment by rudytixhon** [comment]
Hello,
Did you already experiment the integration with Home Assistant?
I receive the following error message when HA is starting : "Platform homekit_controller does not generate unique IDs. ID homekit-Default-SerialNumber-8 already exists"

**Comment by MirandaPoth** [comment]
I'm using this to connect my Niko Home Control 2 installation to Apple Home/Homekit. Right now I don't use Home Assistant, although I might look at it in the future. Not sure what benefits it has?

**Comment by rudytixhon** [comment]
For using only NHC2 there is no added value but if you want to control a larger environment with screens/detectors/meters which are not compatible with Homebridge, Home Assistant (or Jeedom) become interesting. Huge level of customization and possibilities of automation.

**Comment by extric99** [comment]
For people that are on NHC1 and want to use homekit/alexa/google I recommend looking into openhab combined with the homebridge extention homebridge-openhab2-complete. This is also useful for NHC2 who would like to control blinds, fans or thermostats. Openhab is extremely powerful in automating but has somewhat of a steep learning curve. Benefits is that it does not require a connected controller, supports more types and has proven to be rock solid over for me even more than the hue items on my homekit. 

https://community.openhab.org/t/niko-home-control/3482/223
https://community.openhab.org/t/creative-solutions-or-implementations-using-the-nikohome-binding/42215/2

**Comment by geani** [comment]
Yeah I did that to but then I used the openHAB plugin in node-red. It gives you more control over the blinds and you have way more options to. in my opinion.

**Comment by rudytixhon** [comment]
For Home Assistant there is also a 'direct' plugin for NHC2. But I had not success yet to make it work for me.
https://github.com/filipvh/hass-nhc2

**Comment by wvanvlaenderen** [comment]
NHC1 and NHC2 use different protocols, NHC2 is based on MQTT. Please have a look at [nhc2-hobby-api](https://github.com/wvanvlaenderen/nhc2-hobby-api) for addressing NHC2 devices over MQTT.

Options would be to: 
- develop a small node server application acting as a bridge to expose NHC2 devices over a REST API, a plugin for Home Assistant (or other home automation platforms) can be developed to access this API
- access the devices directly over MQTT

**Comment by wvanvlaenderen** [comment]
Closing this as this add-on is about NHC2
