### ISSUE TITLE
cachedAccessories

### ISSUE THREAD

**Issue by WesleyLiekens** [homebridge-nhc2/homebridge-nhc2#2]
The plugin does not support cached accessories, Is this because this is impossible or can this be made in a future update?

Thanks in advance

**Comment by wvanvlaenderen** [comment]
Hi WesleyLiekens

Support for cached accessories is added in 1.1.0. Try updating your plugin
`npm install -g homebridge-nhc2@1.1.0`.

**Comment by WesleyLiekens** [comment]
Brilliant!!
Thank you for this update
