### ISSUE TITLE
A question, not a bug - why are some device names not coming through?

### ISSUE THREAD

**Issue by MirandaPoth** [homebridge-nhc2/homebridge-nhc2#22]
This is a question for people more knowledgeable than me, not a bug - hope it's OK to post it here.

I have 4 switched-generic devices on my Niko system. One of them shows up in the Home app as the correct name ("Water feature") but the other 3 just show as "Switch". 

In the Accessories section of config-UI, these 3 devices show fine with their correct names ("Big garage door", "Small garage door", "Hot water"). Just not in the Home app.

This is rather a security problem for me really, because you can't tell the 3 apart in the app, so it's very easy to press 'Switch' and one of the garage doors open. Not a good thing if you happened to do it last thing at night!

Does anyone have any ideas on what might be causing this and how to fix it?

Thanks :-)

**Comment by wvanvlaenderen** [comment]
Seems like we are mapping a wrong field as the name. 

I've added a sample @ https://github.com/wvanvlaenderen/nhc2-hobby-api/blob/master/samples/log-all-devices.ts to log all devices.

Could you try running it and paste the output?

```
  npm install -g nhc2-hobby-api
  cd samples
  tsc log-all-devices.ts  && node log-all-devices.js 
```

**Comment by MirandaPoth** [comment]
See attached. Not sure if it's a field mapping thing, because 'Water Feature' comes through OK and they appear correctly in the homebridge Config-UI?

Let me know if there's anything else I can do to help.

[log-all-devices.txt](https://github.com/wvanvlaenderen/homebridge-nhc2/files/5340849/log-all-devices.txt)

**Comment by MirandaPoth** [comment]
**Actually** - I think it's something with the Home app on my phone. I just got my husband to check his phone and all the switched-generic devices have the correct names. So nothing for you to do! Sorry to have bothered you.

Do you know what I could do on my phone to try to fix it?

**Comment by MirandaPoth** [comment]
Problem has gone away after killing all apps on my phone and powering off and on again. Closing this issue.
