### ISSUE TITLE
Not all events at MQTT level are received in homebridge-nhc2

### ISSUE THREAD

**Issue by christophevg** [homebridge-nhc2/homebridge-nhc2#23]
https://github.com/wvanvlaenderen/homebridge-nhc2/blob/371a7d519884c4c295347cd0fded05317fa29567/src/nhc2-platform.ts#L69-L71

If I add some logging inside this I only get a response on the first event that is fired from the NHC MQTT server. So I have the impression that something fails to continue to handle the stream of events after that first event.

@wvanvlaenderen maybe this triggers a thought regarding a possible underlying problem with you? 😉  I'm going to try to debug it at the level of nhc2-hobby-api 🤞

**Comment by christophevg** [comment]
Did some digging and this is what I could figure out so far:

1. adding a small sample to nhc2-hobby-api to dump all received events dumps all events triggered from NHC. That part works, no issue to see there.

```javascript
(async () => {
  // simulate same setup as with homebridge-nhc2
  await nhc2.subscribe();
  const nhc2Accessories = await nhc2.getAccessories();
  nhc2.getEvents().subscribe(event => {
    console.log(JSON.stringify(event));
  });
})();
```

2. logging events from the handler doesn't produce all events, very few in fact (1 in 5 on average).

```javascript
    .on('message', (topic: string, message: string) => {
       console.log("%s : %s", topic, message);  // closest I can get to dump events ;-)
       this.events.next(JSON.parse(message.toString()));
     });
```

_Looks like_ something blocks the interaction between nhc2-hobby-api and homebridge-nhc2, or the underlying MQTT connection, or... ?.

Even when running the sample in parallel to the homebridge setup, the sample logs all events, while homebridge-nhc2 only receives a small subset.

**Comment by christophevg** [comment]
More digging ;-)

Found [https://github.com/mqttjs/MQTT.js/issues/644](https://github.com/mqttjs/MQTT.js/issues/644) which gave me the idea to log when `on('connect')` was triggered, and indeed, this get triggered a lot and only events received just after such connect event are received. So the client in nhc2-hobby-api, when used from homebridge-nhc2 disconnects a lot, thus not receiving all events.

Let's see what we can do about that 😉

**Comment by christophevg** [comment]
Found the problem 🤦‍♂️

Because I'm running two instances of Homebridge + homebridge-nhc2, one "production" on a Raspberry Pi and one on my laptop for development purposes, they had the same `clientId`, which caused the server to constantly disconnect the _other_ one when one connected. Changing the `clientId` on the development setup solved the problem.

Consider this documentation which hopefully at least can solve this for someone else in the future 🤣

**Comment by MirandaPoth** [comment]
Good information, thanks!
