### ISSUE TITLE
Wireless Hub update by Niko (December 2021) breaks all functionality

### ISSUE THREAD

**Issue by yannicklips** [homebridge-nhc2/homebridge-nhc2#37]
Early December 2021 there were two updates by Niko for the Wireless Hub. After the second update, all functionality of the HomeBridge plugin v2.0.0 is broken.

I am running HomeBridge v1.3.8 but backtested on v1.3.0 and v1.3.5 with the same result.
My Niko Home Control 2 wireless hub has the latest update from 05/12/2021 (Niko Home Control programmeersoftwareversie
2.13.31085)

There are no error messages in the HomeBridge terminal or in Apple Home, but the statuses are not updating and nothing can be actioned. I have contacted Niko as well, but so far no response.

I checked and the API key is still valid, HomeBridge and Apple Home still believe they work fine, but that actual commands are either not arriving at Niko or no longer being processed.

Homebridge v1.3.8
Node.js Version v16.13.1
Npm Version v8.1.2
@homebridge-nhc2/homebridge-nhc2 v2.0.0

I would greatly appreciate your help as all my automations for lights and switches rely on this plugin.

**Comment by jdecupere** [comment]
Check your IP address of the wireless hub. 
I had the same issue and noticed after the update and reboot, my hub had received another IP address than before. This happened before with updates so I knew the issue. 
Then adjust the IP address in you HB config and restart the bridge
Unfortunately, I do not think there is a way to have the NHC hub get a static address so with every update you better check if the assigned address stayed the same.

**Comment by jdecupere** [comment]
Correcting autocorrect: meant STATIC address, not status of course

**Comment by yannicklips** [comment]
Dear jdecupere, you are a life saver! It indeed seemed that after the Wireless Hub update the device changed it network identificatino (I presume MAC address) and therefore my DCHP server handed out a new IP address out of the pool and kept the old fixed IP reserved for the previous network id from the Wireless Hub. I cleared the reservation and reattached it to the new MAC address. After a restart of HomeBridge all is well again.

Thank you!

**Comment by yannicklips** [comment]
As this was a networking issue only, the issue can be closed. Learning for me that software updates can lead to MAC address updates, my apologies, leaving it on here so other people can learn as well.
