### ISSUE TITLE
Issue with Homebridge and Hoobs with 1.1.0

### ISSUE THREAD

**Issue by Krysbe** [homebridge-nhc2/homebridge-nhc2#4]
**Describe the bug**

I receive this error :

06/05/2020 à 10:32:22 No plugins found.
06/05/2020 à 10:32:22 The requested platform "NHC2" was not registered by any plugin.
06/05/2020 à 10:32:22 Your config.json is requesting the platform "NHC2" which has not been published by any installed plugins.
06/05/2020 à 10:32:22 Bridge is running on port 51826.
06/05/2020 à 10:34:38 Cannot find module 'homebridge'
Require stack:
- /home/hoobs/.hoobs/node_modules/homebridge-nhc2/dist/nhc2-platform.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/plugins.js
- /usr/local/lib/node_modules/@hoobs/hoobs/controllers/system.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
06/05/2020 à 10:34:38 Unable to determine plugin type for "homebridge-nhc2"
06/05/2020 à 10:34:42 Cannot find module 'homebridge'

**Steps To Reproduce**
Install nhc2 in Hoobs
Configure the plugin in Advanced. 

**Library version**

HOOBS Version | 3.2.3
-- | --
Node Version | 12.13.1

Regards, 
Chris

**Comment by wvanvlaenderen** [comment]
Hi Chris

I've added the missing dependencies in #5 
Could you try running homebridge-nhc2@1.1.2?

**Comment by Krysbe** [comment]
Hi, 

Updated. But something seems to be wrong

I have this log 

06/05/2020 à 20:26:27 Loaded plugin "homebridge-nhc2".
06/05/2020 à 20:26:27 The requested platform "NHC2" was not registered by any plugin.
06/05/2020 à 20:26:27 Your config.json is requesting the platform "NHC2" which has not been published by any installed plugins.

here the JSON

    "platforms": [
        {
            "platform": "NHC2",
            "name": "NHC2",
            "host": "xxxxx",
            "password": "xxxxx",
            "plugin_map": {
                "plugin_name": "homebridge-nhc2"
            }
        }
    ]

**Comment by wvanvlaenderen** [comment]
Hi Chris

I am not familiar with HOOBS, but it looks like HOOBS loads plugins a bit different than vanilla Homebridge. In #6 I've fixed the registration of homebridge-nhc2, and I was able to control my NHC2 installation through HOOBS.

![image](https://user-images.githubusercontent.com/7047591/81256990-6413b880-9032-11ea-94f4-deecfbed6807.png)

Could you try again running homebridge-nhc2@1.1.3 ? Your config seems correct, accessories should be auto-discovered after installing the plugin and restarting the service.

Wouter

**Comment by Krysbe** [comment]
It’s working now. Thanks ! 

Do you plan to continue the development of your plugin and integrate sockets, thermostat... ?

Great job thanks to do what Niko refuses to do.

Chris

**Comment by wvanvlaenderen** [comment]
Hi Chris

I do not plan to integrate other NHC2 accessories at the moment because I do not have them in my home setup.

**Comment by oznu** [comment]
Hi @wvanvlaenderen 

I'm just reaching out as I noticed this plugin has included Homebridge as a prod-dependency.

Please beware we are removing the non-type exports from Homebridge in the next release.

https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md#for-developers

> Homebridge now only exports types that are safe to use in your code and won't result in the homebridge library being a runtime dependency. If you have been using types correctly then you will not be impacted by this change.

Const enums are exported as normal and can be safely used as these are replaced by their value when TypeScript is compiled.

Additionally a red warning will be shown in the logs if the plugin has "homebridge" or "hap-nodejs" listed as a production dependency.

https://github.com/homebridge/homebridge/pull/2567

You can test this against your plugin by installing the current beta of homebridge as a devDependency.

If you need any assistance making the changes required please let me know.
